-- ==========================================
-- CLINIVET LINS DATABASE SCHEMA
-- ==========================================


-- ==========================================
-- 1. LEADS
-- ==========================================

CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    tutor_name TEXT NOT NULL,
    pet_name TEXT NOT NULL,
    pet_species TEXT NOT NULL,

    phone TEXT NOT NULL,

    source TEXT DEFAULT 'WhatsApp',

    status TEXT DEFAULT 'Interessado'
        CHECK (status IN (
            'Interessado',
            'Triagem Realizada',
            'Agendado',
            'Concluído'
        ))
);

CREATE INDEX IF NOT EXISTS idx_leads_phone
ON leads(phone);

CREATE INDEX IF NOT EXISTS idx_leads_status
ON leads(status);

CREATE INDEX IF NOT EXISTS idx_leads_created
ON leads(created_at);



-- ==========================================
-- 2. SERVICES
-- ==========================================

CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT UNIQUE NOT NULL,

    category TEXT NOT NULL,

    duration_minutes INT DEFAULT 30,

    price DECIMAL(10,2),

    created_at TIMESTAMPTZ DEFAULT NOW()
);


INSERT INTO services (name, category, duration_minutes) VALUES
('Consulta', 'Regular', 30),
('Vacina', 'Regular', 15),
('Cirurgia Tecidos Moles', 'Urgência', 60),
('Anestesia Inalatória', 'Urgência', 60),
('Ultrassonografia', 'Regular', 30),
('Acupuntura', 'Regular', 45),
('Laserterapia', 'Regular', 20),
('Internação', 'Urgência', 1440),
('Banho e Tosa', 'Regular', 60),
('Venda de Medicamentos', 'Especial', 10),
('Quimioterapia', 'Especial', 60),
('Atestado de Saúde', 'Regular', 20),
('Aferição de Pressão', 'Regular', 15),
('Eletrocardiograma', 'Regular', 30),
('Oxigenioterapia', 'Urgência', 60)

ON CONFLICT (name) DO NOTHING;



-- ==========================================
-- 3. APPOINTMENTS
-- ==========================================

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    lead_id BIGINT NOT NULL
        REFERENCES leads(id)
        ON DELETE CASCADE,

    service_id BIGINT NOT NULL
        REFERENCES services(id),

    appointment_time TIMESTAMPTZ NOT NULL,

    duration_minutes INT NOT NULL,

    status TEXT DEFAULT 'Confirmado'
        CHECK (status IN (
            'Confirmado',
            'Cancelado',
            'Concluído'
        )),

    google_event_id TEXT,

    notes TEXT
);


CREATE INDEX IF NOT EXISTS idx_appointments_time
ON appointments(appointment_time);

CREATE INDEX IF NOT EXISTS idx_appointments_lead
ON appointments(lead_id);

CREATE INDEX IF NOT EXISTS idx_appointments_status
ON appointments(status);



-- ==========================================
-- 4. VIEWS
-- ==========================================

CREATE OR REPLACE VIEW daily_appointments AS
SELECT
    a.appointment_time::TIME AS horario,
    l.tutor_name AS tutor,
    l.pet_name AS pet,
    l.pet_species AS especie,
    s.name AS servico,
    a.status
FROM appointments a
JOIN leads l ON a.lead_id = l.id
JOIN services s ON a.service_id = s.id
WHERE a.appointment_time::DATE = CURRENT_DATE
ORDER BY a.appointment_time ASC;



CREATE OR REPLACE VIEW conversion_funnel AS
SELECT
    COUNT(*) AS total_leads,

    COUNT(*) FILTER (
        WHERE status = 'Agendado'
    ) AS agendamentos_confirmados,

    ROUND(
        (
            COUNT(*) FILTER (WHERE status = 'Agendado')::NUMERIC
            /
            NULLIF(COUNT(*),0)
        ) * 100,
    2) AS taxa_conversao_percent
FROM leads;



CREATE OR REPLACE VIEW top_services AS
SELECT
    s.name AS servico,
    COUNT(a.id) AS total_agendamentos
FROM services s
LEFT JOIN appointments a
ON s.id = a.service_id
GROUP BY s.name
ORDER BY total_agendamentos DESC;



CREATE OR REPLACE VIEW cold_leads_followup AS
SELECT
    tutor_name,
    pet_name,
    phone,
    created_at AS data_contato
FROM leads
WHERE status = 'Interessado'
AND created_at < NOW() - INTERVAL '24 hours'
ORDER BY created_at DESC;