-- Migration: calendar CRUD + pet history support
-- Date: 2026-03-09

BEGIN;

CREATE TABLE IF NOT EXISTS pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_phone TEXT NOT NULL,
    name TEXT NOT NULL,
    species TEXT,
    breed TEXT,
    age TEXT,
    weight DOUBLE PRECISION,
    size TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pets_tutor_phone
ON pets(tutor_phone);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pets_tutor_phone_name
ON pets(tutor_phone, name);

ALTER TABLE IF EXISTS appointments
    ADD COLUMN IF NOT EXISTS pet_id BIGINT REFERENCES pets(id);

CREATE INDEX IF NOT EXISTS idx_appointments_pet_id
ON appointments(pet_id);

CREATE TABLE IF NOT EXISTS consultations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
    symptoms TEXT,
    diagnosis TEXT,
    treatment TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_consultations_pet_id
ON consultations(pet_id);

CREATE INDEX IF NOT EXISTS idx_consultations_appointment_id
ON consultations(appointment_id);

CREATE TABLE IF NOT EXISTS vaccines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    vaccine_name TEXT NOT NULL,
    date_applied DATE NOT NULL,
    next_due_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vaccines_pet_id
ON vaccines(pet_id);

CREATE INDEX IF NOT EXISTS idx_vaccines_next_due_date
ON vaccines(next_due_date);

COMMIT;
